### ISSUE TITLE
Startup and exit issues

### ISSUE THREAD

**Issue by quirm** [jupyterlab/jupyterlab-desktop#170]
This project is really terrific. I was using nteract for a while but the chance to use jupyter lab in the same convenient way as nteract is much better. What is the state of the project? Is it being still actively developed?

I see two issues on the current master branch.

`registry.ts@_getSubEnvironmentsFromRoot:324` is trying to get all `envs` paths:
```
private _getSubEnvironmentsFromRoot(rootPath: string): Promise<Registry.IPythonEnvironment[]> {
    let subEnvironmentsFolder = join(rootPath, 'envs');
    ...
```

This causes a problem that the app always asks for a path on its startup. In my case, I don't even have `envs` folder (I have recently made a clean conda installation). When I change this line to `let subEnvironmentsFolder = rootPath;`, it will work but I guess other people could face some problems.

The second issue is when I try to quit the app. Steps to reproduce:
1. open an app (bundled macos app or just a built development version)
2. run a cell in any notebook to hook the kernel
3. try to quit the app with confirmation - `CMD + Q` or just Quit from Dock

It will do nothing and after a few seconds throw an error message in jupyter lab.

![image](https://user-images.githubusercontent.com/236249/55158219-ab0c5a80-515e-11e9-8f04-60f90a86c858.png)

There are also error messages:
```
[13:38:23.628] [info] Kernel: reconnecting (bac20d1c-0bac-4821-996d-005f3b37a03a)
[13:38:23.628] [error] Connection lost, reconnecting in 1 seconds.
[13:38:23.628] [info] Kernel: reconnecting (3e5d038e-d25b-4823-991c-43cab6626c1b)
[13:38:23.628] [error] Connection lost, reconnecting in 1 seconds.
[13:38:23.628] [info] Kernel: reconnecting (3e5d038e-d25b-4823-991c-43cab6626c1b)
[13:38:23.629] [error] Connection lost, reconnecting in 1 seconds.
[13:38:24.630] [info] Starting WebSocket: ws://localhost:8888/api/kernels/bac20d1c-0bac-4821-996d-005f3b37a03a
[13:38:24.631] [info] Starting WebSocket: ws://localhost:8888/api/kernels/3e5d038e-d25b-4823-991c-43cab6626c1b
[13:38:24.632] [info] Starting WebSocket: ws://localhost:8888/api/kernels/3e5d038e-d25b-4823-991c-43cab6626c1b
[13:38:26.884] [error] Error: Invalid response: 404 Not Found
    at new ResponseError (file:///Users/username/Projects/jupyterlab_app/build/browser.bundle.js:21575:28)
    at file:///Users/username/Projects/jupyterlab_app/build/browser.bundle.js:57591:23
    at <anonymous>
```

At this point, it's impossible to quit the app. It needs to be force-quit.

**Comment by mbektas** [comment]
an issue for old app.
