### ISSUE TITLE
Prebuilt extension axlair/jupyterlab-vim does not load anymore

### ISSUE THREAD

**Issue by dirkroorda** [jupyterlab/jupyterlab-desktop#379]
## Description

`jupyterlab-vim` is a prebuilt extension, installable by `pip install jupyterlab-vim`.

Yet it does not work in the newest version of JupyterLab desktop (3.2.5-2)
In the previous version of JupyterLab desktop I managed to get it working after a bit of refreshing the page.

## Reproduce

1. install jupyterlab-desktop, version (single user, so packages can be installed)
2. in a code cell: `%pip install jupyterlab-vim`; it will run successfully
3. restart the kernel, refresh the page, restart the app
4. open a notebook and observe that jupyterlab-vim does not work; we are not in vim normal mode, and we do not get there by pressing Esc.

<img width="139" alt="bad" src="https://user-images.githubusercontent.com/1374704/146755827-6b466096-3783-4b5b-89be-d81bf7edea78.png">

## Expected behaviour

In step 4 one should in vim normal mode, having a green block cursor, and pressing `i` or `a` should bring you in insert mode with
a thin cursor.

This is from ordinary jupyterlab:

Vim normal mode:

<img width="178" alt="good" src="https://user-images.githubusercontent.com/1374704/146755261-c7251233-7a1e-45b6-a596-634c375595ec.png">

after pressing `a` we are in insert mode:

<img width="182" alt="good2" src="https://user-images.githubusercontent.com/1374704/146755464-7d2a97da-fc8e-4846-8ecd-a75071ad94ae.png">

## Observations

It happens both in the bundled Python environment (where I `%pip install jupyterlab-vim`) as in my system python environment (python 3.10.0 with jupyterlab-vim already installed).

In the developer tools (View->Toggle Developer Tools) there is something irregular. See below.

Failed to load resource: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js the server responded with a status of 404 (Not Found)

Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_codemirror_keymap_vim_js failed.
(error: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js)
    at Object.__webpack_require__.f.j (browser.bundle.js:310168)
    at browser.bundle.js:309590
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (browser.bundle.js:309589)
    at CodeMirrorSingleton.ensureVimKeymap (browser.bundle.js:43145)
    at localhost:8888/lab/extensions/@axlair/jupyterlab_vim/static/568.2a96b0eb36f0a81bc69a.js:1

11:13:13.051 › Loading chunk vendors-node_modules_codemirror_keymap_vim_js failed.
(error: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js)

## Context

- Operating system: Macos 11.6.1 (BigSur)
- JupyterLab-Desktop version: 3.2.5-2
- Installer: JupyterLab-Setup-macOS.pkg

<details><summary>Troubleshoot Output</summary>
I do not do this, because it lists my system python, although I am working in the prebuilt environment!

Here you see the bottom bar indicating that I'm in the prebuilt environment, but it lists `python-Levenshtein` which is a module from my system environment.
<img width="656" alt="hm" src="https://user-images.githubusercontent.com/1374704/146756840-ae15ff07-5534-4d03-8eb0-ebc7f3afd1c1.png">

</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>
<pre>
Failed to load resource: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js the server responded with a status of 404 (Not Found)

Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_codemirror_keymap_vim_js failed.
(error: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js)
    at Object.__webpack_require__.f.j (browser.bundle.js:310168)
    at browser.bundle.js:309590
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (browser.bundle.js:309589)
    at CodeMirrorSingleton.ensureVimKeymap (browser.bundle.js:43145)
    at localhost:8888/lab/extensions/@axlair/jupyterlab_vim/static/568.2a96b0eb36f0a81bc69a.js:1

11:13:13.051 › Loading chunk vendors-node_modules_codemirror_keymap_vim_js failed.
(error: http://localhost:8888/vendors-node_modules_codemirror_keymap_vim_js.browser.bundle.js)

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>
(I have replaced the path to my home directory by `~`).
<pre>
Paste the logs from the mian.log file here.
[2021-12-20 12:02:00.979] [info]  In production mode
[2021-12-20 12:02:00.982] [info]  Logging to file (~/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2021-12-20 12:02:01.042] [error] (node:3454) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2021-12-20 12:02:03.769] [error] (node:3454) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
[2021-12-20 12:02:04.496] [info]  Jupyter Server initialization message: ~/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '' instead of '""' if you require traitlets >=5.
  warn(
~/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '*' instead of '"*"' if you require traitlets >=5.
  warn(
[I 2021-12-20 12:02:04.496 ServerApp] jupyterlab | extension was successfully linked.

[2021-12-20 12:02:04.737] [info]  Jupyter Server initialization message: [I 2021-12-20 12:02:04.737 ServerApp] nbclassic | extension was successfully linked.

[2021-12-20 12:02:04.770] [info]  Jupyter Server initialization message: [I 2021-12-20 12:02:04.770 ServerApp] nbclassic | extension was successfully loaded.

[2021-12-20 12:02:04.771] [info]  Jupyter Server initialization message: [I 2021-12-20 12:02:04.771 LabApp] JupyterLab extension loaded from ~/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/jupyterlab
[I 2021-12-20 12:02:04.771 LabApp] JupyterLab application directory is ~/Applications/JupyterLab.app/Contents/Resources/jlab_server/share/jupyter/lab

[2021-12-20 12:02:04.775] [info]  Jupyter Server initialization message: [I 2021-12-20 12:02:04.775 ServerApp] jupyterlab | extension was successfully loaded.

[2021-12-20 12:02:04.776] [info]  Jupyter Server initialization message: [I 2021-12-20 12:02:04.776 ServerApp] Serving notebooks from local directory: ~

</pre>
</details>

By the way: I cannot pip-*uninstall* modules from within the desktop app, because pip asks for confirmation, and there is no way to answer with `Y`.

When uninstalling by means of `%pip --no-input uninstall jupyterlab-vim` I get an error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 97, in run
    uninstall_pathset = req.uninstall(
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 671, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 378, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 418, in _allowed_to_proceed
    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 187, in ask
    _check_no_input(message)
  File "/Users/werk/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 179, in _check_no_input
    raise Exception(
Exception: No input was expected ($PIP_NO_INPUT set); question: Proceed (Y/n)? 
```

So I could not experiment with uninstalling and reinstalling the package again.

Screenshot:
<img width="1311" alt="bug" src="https://user-images.githubusercontent.com/1374704/146754986-06053446-1886-4638-abf0-29d8fbd3621e.png">

**Comment by krassowski** [comment]
Thank you for they report. I can reproduce this and will take a look at fixing this over the weekend.

**Comment by kunchenguid** [comment]
@krassowski any luck with this?

**Comment by rchavp** [comment]
Any update on this issue. I've tried the last 6 versions and all of them stall after installing the vim plugin.

Alternatively, any pointers on how to troubleshoot this ourselves then?

Thanks.

**Comment by mbektas** [comment]
@rchavp is this still an issue with the latest version 3.6.1-1?

**Comment by dirkroorda** [comment]
I gave the latest version a try, a couple of days ago.
I had some kernel trouble when using my existing Python.
Still jupyterlab-vim does not work, don't see clear error messages, and there is no extensions tab on the interface.

So, for the time being I give up 
For me personally I do not see any advantage of the Desktop version above the regular version.

**Comment by notluquis** [comment]
The version pin in this report is no longer what blocks it. jupyterlab-vim 4.1.4, released September 2024, requires `jupyterlab>=4.2,<5`, and the bundled environment is on 4.6.2. The 2021 reports were against JupyterLab 3 and a jupyterlab-vim from that era.

That says the incompatibility is gone, not that the extension loads, and nobody has run it since. A retest on 4.6.2-1, installing jupyterlab-vim into the environment the app uses, would settle whether there is still something here. Without one this stays open on evidence that is four years old.
