### ISSUE TITLE
Profile variables in `~/.zshrc` are not loaded when launching JupyterLab through launcher

### ISSUE THREAD

**Issue by harripj** [jupyterlab/jupyterlab-desktop#437]
## Description

When opening `jupyterlab.app` from the app launcher on MacOS, ie. clicking the icon, variables stored in `.zshrc` such as `$PYTHONPATH` are not loaded into the notebook interpreter such that `$PYTHONPATH` variables are not found in `sys.path`. When launching from the terminal, ie. `jlab`, these variables are loaded correctly (although loaded twice in the integrated terminal).

I would expect that the `.zshrc` variables are loaded regardless of how the app is opened.

Possibly related: https://github.com/jupyterlab/jupyterlab/issues/11884

Opening JupyterLab by clicking icon
-------------------------------------
When opening a notebook and looking at `sys.path` my profile variables are not loaded. `!echo $PYTHONPATH` shows that the variable is unset:
![image](https://user-images.githubusercontent.com/16853829/161505282-996eb272-3bd0-4492-9682-832ea0e533f6.png)

Interestingly `$PYTHONPATH` is set when opening the integrated terminal.

![image](https://user-images.githubusercontent.com/16853829/161499401-1312c9a4-2186-4c4e-a1da-d06fb5b27b55.png)

Opening JupyterLab through terminal `jlab`
-------------------------------------------
Profile variables are set in the notebook and `PYTHONPATH` is loaded into `sys.path`.
![image](https://user-images.githubusercontent.com/16853829/161506943-0c7103d0-706f-4398-9c3c-8f97661cb657.png)

In the integrated terminal my profile variables appear to have been loaded twice, perhaps this is related to the problem:
![image](https://user-images.githubusercontent.com/16853829/161506536-1ad5c412-608f-46a9-b220-decdf6d2d2f1.png)

## Reproduce

1. Define some variables in `~/.zshrc`, eg. `PYTHONPATH`
2. Open JupyterLab.app from launcher to find profile variables not loaded.
3. Open JupyterLab.app from terminal (`zsh`), ie. `jlab`, to find profile variables loaded (and duplicated in integrated terminal).

## Expected behavior

`~/.zshrc` profile variables are loaded correctly regardless of how app was launched.

## Context

- Operating System and version: MacOS 12.3.1 Intel
- JupyterLab-Desktop version: 3.3.2-2
- Installer: .dmg

<details><summary>Troubleshoot Output</summary>
App opened from launcher:

[jupyter troubleshoot launcher.txt](https://github.com/jupyterlab/jupyterlab-desktop/files/8408263/jupyter.troubleshoot.launcher.txt)

App opened from terminal (`jlab`):
[jupyter troubleshoot jlab.txt](https://github.com/jupyterlab/jupyterlab-desktop/files/8408252/jupyter.troubleshoot.jlab.txt)
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

`main.log`:
<pre>
[2022-04-01 16:36:19.661] [info]  In production mode
[2022-04-01 16:36:19.667] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:36:19.732] [error] (node:20583) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 16:37:14.439] [info]  In production mode
[2022-04-01 16:37:14.443] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:37:14.503] [error] (node:20695) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 16:37:21.251] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 16:37:33.178] [info]  In production mode
[2022-04-01 16:37:33.181] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:37:33.241] [error] (node:20837) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 16:37:39.883] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 16:37:51.075] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/jupyterlab/jupyterlab-desktop/issues
[2022-04-01 16:38:08.796] [info]  In production mode
[2022-04-01 16:38:08.799] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:38:08.856] [error] (node:20948) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 16:38:15.560] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 16:52:22.978] [info]  In production mode
[2022-04-01 16:52:22.982] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:52:23.047] [error] (node:22438) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 16:52:30.633] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 16:54:46.994] [info]  In production mode
[2022-04-01 16:54:46.996] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 16:54:47.049] [error] (node:22970) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:32:47.152] [info]  In production mode
[2022-04-01 23:32:47.161] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 23:32:47.212] [error] (node:48543) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:32:55.475] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 23:33:05.274] [info]  In production mode
[2022-04-01 23:33:05.277] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 23:33:05.325] [error] (node:48639) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:33:09.861] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 23:33:14.158] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/jupyterlab/jupyterlab-desktop/issues
[2022-04-01 23:42:01.492] [info]  In production mode
[2022-04-01 23:42:01.495] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 23:42:01.548] [error] (node:50945) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:42:07.797] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-01 23:43:08.609] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/jupyterlab/jupyterlab-desktop/issues
[2022-04-01 23:46:36.893] [info]  In production mode
[2022-04-01 23:46:36.896] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 23:46:36.949] [error] (node:52079) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:50:20.679] [info]  In production mode
[2022-04-01 23:50:20.682] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-01 23:50:20.733] [error] (node:52518) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:50:25.628] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-04-04 09:44:14.860] [info]  In production mode
[2022-04-04 09:44:14.872] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 09:44:14.941] [error] (node:43179) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 09:46:10.773] [info]  In production mode
[2022-04-04 09:46:10.777] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 09:46:10.839] [error] (node:43462) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 09:50:46.850] [info]  In production mode
[2022-04-04 09:50:46.854] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 09:50:46.918] [error] (node:43975) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 10:34:08.109] [info]  In production mode
[2022-04-04 10:34:08.112] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 10:34:08.172] [error] (node:46055) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 10:44:00.372] [error] (node:46055) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'paste')
    at KeyboardShortcutManager.paste (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/shortcuts.js:67:55)
    at Object.showErrorBox (node:electron/js2c/browser_init:49:5727)
    at node:electron/js2c/browser_init:197:763
[2022-04-04 10:44:00.373] [error] (node:46055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2022-04-04 10:47:51.018] [info]  In production mode
[2022-04-04 10:47:51.022] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 10:47:51.087] [error] (node:46811) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 10:54:42.528] [info]  In production mode
[2022-04-04 10:54:42.531] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 10:54:42.592] [error] (node:47268) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-04 10:55:03.080] [info]  In production mode
[2022-04-04 10:55:03.084] [info]  Logging to file (/Users/myuser/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-04-04 10:55:03.145] [error] (node:47563) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
</pre>
</details>

**Comment by mbektas** [comment]
@harripj you will be able to set environment variables with this [upcoming changes](https://github.com/jupyterlab/jupyterlab-desktop/pull/588).

**Comment by harripj** [comment]
@mbektas thank you for the update! Will there be the option to automatically source terminal profile scripts? Looking forward to trying it out 😄

**Comment by mbektas** [comment]
@harripj the new version is now available. it doesn't source the profile scripts but you can set environment variables. please try it out and update the issue. instructions are in the [user guide](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#server-environment-variables).
