### ISSUE TITLE
Jupyterlab Desktop still pops up the setup window after setting up the python environment

### ISSUE THREAD

**Issue by aoaim** [jupyterlab/jupyterlab-desktop#454]
## Description

 When I download and open Jupyterlab Desktop, a window pops up to set the python environment. When I select python in this window and then select apply & restart, this window will still pop up. Loop . I'm using a MacBook Pro 2021, M1 Pro Chip.

## Context

First time, i check the log:

```
[2022-05-30 14:05:58.987] [info]  In production mode
[2022-05-30 14:05:58.997] [info]  Logging to file (/Users/xxx/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-05-30 14:05:59.165] [error] (node:39302) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-05-30 14:05:59.403] [info]  feedURL https://update.electronjs.org/jupyterlab/jupyterlab-desktop/darwin-x64/3.3.4-2
[2022-05-30 14:05:59.404] [info]  requestHeaders { 'User-Agent': 'update-electron-app/2.0.1 (darwin: x64)' }
[2022-05-30 14:05:59.489] [error] Error: Command failed: ln -s /Applications/JupyterLab.app/Contents/Resources/app/jlab /usr/local/bin/jlab
ln: /usr/local/bin/jlab: Permission denied

    at checkExecSyncError (node:child_process:835:11)
    at Object.execSync (node:child_process:909:15)
    at Object.execSync (node:electron/js2c/asar_bundle:5:12692)
    at setupJLabCommand (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/main.js:177:25)
    at /Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/main.js:192:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-30 14:05:59.536] [info]  checking-for-update
[2022-05-30 14:06:01.132] [info]  update-not-available
[2022-05-30 14:06:48.784] [error] Error: JupyterLab did not save state successfully
    at /Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/app.js:233:46
```
I realized that this was a permission problem, so I did it manually: `sudo ln -s /Applications/JupyterLab.app/Contents/Resources/app/jlab /usr/local/bin/jlab`, and then i try to restart jupyterlab desktop. 

However, when I opened it for the second time, there was still a window to set up the python environment. After setting it up, I still couldn't enter the jupyterlab desktop. I checked the log and found that:

```
[2022-05-30 14:23:19.372] [info]  In production mode
[2022-05-30 14:23:19.382] [info]  Logging to file (/Users/xxx/Library/Logs/jupyterlab-desktop/main.log) at 'false' level
[2022-05-30 14:23:19.574] [error] (node:42799) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-05-30 14:23:19.828] [info]  feedURL https://update.electronjs.org/jupyterlab/jupyterlab-desktop/darwin-x64/3.3.4-2
[2022-05-30 14:23:19.829] [info]  requestHeaders { 'User-Agent': 'update-electron-app/2.0.1 (darwin: x64)' }
[2022-05-30 14:23:19.940] [info]  checking-for-update
[2022-05-30 14:23:20.931] [info]  update-not-available
[2022-05-30 14:23:48.988] [error] Error: JupyterLab did not save state successfully
    at /Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/app.js:233:46
```

i donnot know how to resolve it.

- Operating System and version: macOS Monterey 12.4
- JupyterLab-Desktop version: v3.3.4-2
- Installer: JupyterLab-macOS.zip

**Comment by tfiner** [comment]
I have the exact same issue, and I also tried v3.3.4-1.

**Comment by mbektas** [comment]
JupyterLab Desktop saves the configuration in file `~/Library/jupyterlab-desktop/jupyterlab-desktop-data` as JSON on macOS. Python path you select is saved in there as well with `pythonPath` key. Looks like you don't have permission to write the configuration file. Can you check?

**Comment by aoaim** [comment]
> JupyterLab Desktop saves the configuration in file `~/Library/jupyterlab-desktop/jupyterlab-desktop-data` as JSON on macOS. Python path you select is saved in there as well with `pythonPath` key. Looks like you don't have permission to write the configuration file. Can you check?

Thanks. I found the `~/Library/jupyterlab-desktop/` does not exist, than I created it manually, and now it can work.
