### ISSUE TITLE
Cannot load or create notebook, Windows Jupyterlab desktop app

### ISSUE THREAD

**Issue by msghens** [jupyterlab/jupyterlab-desktop#499]
![image](https://user-images.githubusercontent.com/13319506/194913363-0e6ba8eb-cf0a-49d6-8766-98000f10fc43.png)

![image](https://user-images.githubusercontent.com/13319506/194913424-ebd7500d-bd46-4efe-a346-6d1b850e0bea.png)

### Main Log

[2022-10-10 06:21:30.615] [info]  In production mode
[2022-10-10 06:21:30.619] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 06:21:30.664] [error] (node:9876) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-10-10 06:24:03.006] [info]  In production mode
[2022-10-10 06:24:03.011] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 06:24:03.057] [error] (node:19516) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-10-10 06:27:42.983] [info]  In production mode
[2022-10-10 06:27:42.988] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 06:27:43.038] [error] (node:20044) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-10-10 06:40:00.943] [info]  In production mode
[2022-10-10 06:40:00.948] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 06:40:00.994] [error] (node:23704) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-10-10 06:40:07.122] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-10-10 06:40:07.125] [error] (node:23704) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at Object.b.send (node:electron/js2c/browser_init:165:2482)
    at C:\JupyterLab\resources\app.asar\build\out\asyncremote\main.js:69:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-10 06:40:07.128] [error] (node:23704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[2022-10-10 09:14:55.523] [info]  In production mode
[2022-10-10 09:14:55.529] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 09:14:55.588] [error] (node:13716) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-10-10 09:20:36.597] [info]  In production mode
[2022-10-10 09:20:36.603] [info]  Logging to file (C:\Users\msghe\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-10-10 09:20:36.649] [error] (node:35100) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)

### Render log

[2022-10-10 06:27:57.200] [debug] Starting application in workspace: "default"
[2022-10-10 06:28:04.722] [warn]  Showing error: Error: Unexpected error while saving file: Untitled8.ipynb [WinError 2] The system cannot find the file specified: 'C:\\Users\\msghe\\.~Untitled8.ipynb' -> 'C:\\Users\\msghe\\Untitled8.ipynb'
    at Function.create (http://localhost:54460/desktop-app-assets/browser.bundle.js:106471:28)
    at async Drive.newUntitled (http://localhost:54460/desktop-app-assets/browser.bundle.js:102537:25)
[2022-10-10 09:15:12.503] [debug] Starting application in workspace: "default"
[2022-10-10 09:15:22.692] [warn]  Showing error: Error: Unreadable Notebook: C:\Users\msghe\Untitled.ipynb TypeError("__init__() got an unexpected keyword argument 'capture_validation_error'")
    at Function.create (http://localhost:49403/desktop-app-assets/browser.bundle.js:106471:28)
    at async Drive.get (http://localhost:49403/desktop-app-assets/browser.bundle.js:102481:25)
[2022-10-10 09:15:22.703] [error] Failed to initialize the context with 'notebook' for Untitled.ipynb Error: Unreadable Notebook: C:\Users\msghe\Untitled.ipynb TypeError("__init__() got an unexpected keyword argument 'capture_validation_error'")
    at Function.create (http://localhost:49403/desktop-app-assets/browser.bundle.js:106471:28)
    at async Drive.get (http://localhost:49403/desktop-app-assets/browser.bundle.js:102481:25)
[2022-10-10 09:20:46.110] [debug] Starting application in workspace: "default"
[2022-10-10 09:21:01.954] [warn]  Showing error: Error: Unexpected error while saving file: Untitled9.ipynb [WinError 2] The system cannot find the file specified: 'C:\\Users\\msghe\\.~Untitled9.ipynb' -> 'C:\\Users\\msghe\\Untitled9.ipynb'
    at Function.create (http://localhost:49596/desktop-app-assets/browser.bundle.js:106471:28)
    at async Drive.newUntitled (http://localhost:49596/desktop-app-assets/browser.bundle.js:102537:25)

**Comment by msghens** [comment]
An old version of python with a deprecated version of Node.js was in %APPDATA% directory. Jupyterlab was using that instead of the newly installed python.
