### ISSUE TITLE
jlab app server installation fails, Win11, v3.6.1-1

### ISSUE THREAD

**Issue by black-snow** [jupyterlab/jupyterlab-desktop#587]
## Description

JupyterLab installation succeeded but the built-in app server installer does not. It first shows some package error, that you can ignore (or retry but that doesn't help), and it then fails with:

![grafik](https://user-images.githubusercontent.com/579733/219959412-cce3cdec-5351-4809-aae8-facdaffc1b1b.png)

## Reproduce

1. uninstall old jlab and jupyter
2. download 3.6.1-1 for windows
3. install
4. start jupyter
5. click on the built-in installer in the footer of the new welcome screen
6. install "just for me"

## Expected behavior

Successful install

## Context

- Operating System and version: Win11 10.0.22621 Build 22621, x64
- JupyterLab-Desktop version: v3.6.1-1
- Installer: .exe

<details><summary>Logs (required for issues with loading, server and startup)</summary>
<pre>
[2023-02-19 16:49:04.120] [info]  In production mode
[2023-02-19 16:49:04.127] [info]  Logging to file (C:\Users\xxx\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2023-02-19 16:49:04.194] [error] (node:13108) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2023-02-19 16:49:22.890] [verbose] Starting application in workspace: "default"
[2023-02-19 16:52:16.235] [error] Failed to create free server Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-19 16:52:16.238] [error] (node:23332) UnhandledPromiseRejectionWarning: Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2023-02-19 16:52:16.238] [error] (node:23332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2023-02-19 16:54:32.429] [error] Error: Installer Exit: 2
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\app.js:470:50)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2023-02-19 16:54:40.169] [error] Failed to create free server Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-19 16:54:40.173] [error] (node:17788) UnhandledPromiseRejectionWarning: Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2023-02-19 16:54:40.174] [error] (node:17788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2023-02-19 16:54:56.518] [error] (node:17788) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
</pre>
</details>

**Comment by mbektas** [comment]
I just tested on a Windows 11 virtual machine but couldn't reproduce the issue. Can you provide more info about your system? Is it an Intel CPU?

**Comment by black-snow** [comment]
@mbektas 

> AMD Ryzen 7 PRO 5850U with Radeon Graphics        1.90 GHz

I can include a screenshot of the first error (warning, actually) if that helps. It doesn't seem right, that you can hit "ignore" on that first error.

**Comment by mbektas** [comment]
Can you try running the server installer directly and when JupyterLab Desktop is closed. possibly with elevated permissions if regulat user permissions doesn't work.
It is located at `C:\JupyterLab\resources\env_installer\JupyterLabDesktopAppServer-3.6.1-1-Windows-x86_64.exe`

**Comment by black-snow** [comment]
@mbektas 

Same behaviour wenn running unprivileged (don't want to install it for all users):
![grafik](https://user-images.githubusercontent.com/579733/220641306-8a8eba65-d13c-4f70-a732-27c09bda4061.png)

**Comment by JasonWeill** [comment]
I notice that @black-snow is running a German version of Windows — are we sure we're using localized directory names in the installer? Windows sometimes uses different directory names in different language versions of the OS.

**Comment by black-snow** [comment]
True.

`3.5` worked fine, btw.

**Comment by mbektas** [comment]
> I notice that @black-snow is running a German version of Windows — are we sure we're using localized directory names in the installer? Windows sometimes uses different directory names in different language versions of the OS.

in the top screenshot installation directory is shown. It doesn't have any special characters.

@black-snow do you see an `install.log` file in your server installation directory? (`...Roaming\jupyterlab-desktop\jlab_server`), if so can you check if that provides any details on the error?

**Comment by black-snow** [comment]
@mbektas there's no log there ...

![grafik](https://user-images.githubusercontent.com/579733/221839620-f5826bc6-cb17-4c47-beaf-eef0c76d61f1.png)

**Comment by JasonWeill** [comment]
@mbektas What other info might help to triage this issue?

**Comment by mbektas** [comment]
@black-snow does the full path to jlab_server contain any spaces or non-english characters?
can you try installing to another directory like `C:/jlab_server`.

**Comment by black-snow** [comment]
@mbektas nope, nothing special there - just my Win home dir and my username is just ASCII letters.

On vacation atm so I can't give it a try.

**Comment by JasonWeill** [comment]
@black-snow Any updates on this?

**Comment by black-snow** [comment]
Tried 3.6.1-1:

![grafik](https://user-images.githubusercontent.com/579733/234387574-f753898d-5862-4e39-a85e-545a020243c6.png)

and

![grafik](https://user-images.githubusercontent.com/579733/234387938-193690ad-41bf-4fa6-bf56-b3cc58d19327.png)

**Comment by black-snow** [comment]
Reinstalled "for all users" to `c:\jlab_server` and the install went through. JupyterLab now ain't seem to pick up the installation though - always displays the footer.

**Comment by mbektas** [comment]
@black-snow did you set the Python executable in your installation path as the custom environment as described [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#to-change-the-default-python-environment)?

**Comment by black-snow** [comment]
@mbektas I don't get the question. I run the installer, then start up jupyter lab and hit "Install using the bundled installer" here:
![grafik](https://user-images.githubusercontent.com/579733/235809310-74a3e9c8-0ca3-4bb5-9b0f-e6976b1e28b7.png)

**Comment by mbektas** [comment]
@black-snow I meant setting the installation at `c:\jlab_server` as the default Python environment. In the footer area of your screenshot, you can see `Change the default Python environment`. You can click that, go the server tab and select python executable (must be in `c:\jlab_server\python.exe`) as shown [here for macOS](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/media/server-settings-custom-python-env.png) and restart.

**Comment by black-snow** [comment]
Will give it a fresh shot with the new 3.6.3-2.

**Comment by mbektas** [comment]
glad to hear that!
