### ISSUE TITLE
micromamba environments not supported

### ISSUE THREAD

**Issue by astrojuanlu** [jupyterlab/jupyterlab-desktop#596]
## Description

micromamba environments are not supported.

## Reproduce

1. Add new interpreter located in a micromamba environment
2. On the "select conda base environment" dialog, select the micromamba root directory
3. Observe a "Failed to create session! Invalid base conda environment" message.

## Expected behavior

micromamba environments work.

## Context

- Operating System and version: macOS Ventura
- JupyterLab-Desktop version: 3.6.1-2
- Installer: `.dmg`

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>

```
juan_cano@M-PH9T4K3P3C ~> echo "" > ~/Library/Logs/jupyterlab-desktop/main.log
juan_cano@M-PH9T4K3P3C ~> /Applications/JupyterLab.app/Contents/MacOS/JupyterLab --log-level=debug --verbose 4 --trace-warnings
ln: /usr/local/bin/jlab: Permission denied
2023-02-27 07:08:35.620 JupyterLab[17926:261519] +[CATransaction synchronize] called within transaction
juan_cano@M-PH9T4K3P3C ~> cat ~/Library/Logs/jupyterlab-desktop/main.log

[2023-02-27 07:08:30.427] [error] Error: Command failed: ln -s /Applications/JupyterLab.app/Contents/Resources/app/jlab /usr/local/bin/jlab
ln: /usr/local/bin/jlab: Permission denied

    at checkExecSyncError (node:child_process:865:11)
    at Object.execSync (node:child_process:936:15)
    at Object.execSync (node:electron/js2c/asar_bundle:2:12711)
    at setupJLabCommand (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/main.js:151:29)
    at /Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/main.js:199:9
[2023-02-27 07:08:33.061] [error] Failed to start server Failed to activate conda environment
[2023-02-27 07:08:36.454] [error] Failed to start server Invalid base conda environment
[2023-02-27 07:08:36.466] [error] (node:17926) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'protocol')
    at new LabView (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/labview/labview.js:60:50)
    at SessionWindow._loadLabView (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/sessionwindow/sessionwindow.js:282:25)
    at SessionWindow._updateContentView (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/sessionwindow/sessionwindow.js:697:18)
    at IpcMainImpl.<anonymous> (/Applications/JupyterLab.app/Contents/Resources/app.asar/build/out/main/sessionwindow/sessionwindow.js:429:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2023-02-27 07:08:36.467] [error] (node:17926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

</pre>
</details>

**Comment by arriyaz** [comment]
Please add micromamba environment support in JupyterLab desktop.
I have been using JupyterLab Desktop for conda environments, and it was easy to setup the custom PATH for python.
But, I found micromamba is more faster than conda that's why I switched to micromamba. But, now I can't use jupyterlab desktop as it can't detect the "micromamba base environment".

**Comment by martinRenou** [comment]
I was also looking for this! I'd be happy to look into making a PR for this.

**WORKAROUND: I could make it work by simply doing `export CONDA_EXE=$HOME/.local/bin/micromamba` prior to starting `jupyterlab-desktop`.**
