### ISSUE TITLE
Jupyter Server process terminated before the initialization completed

### ISSUE THREAD

**Issue by samuelvw01** [jupyterlab/jupyterlab-desktop#653]
## Description

When I click on New session it shows error "Failed to create session! Jupyter Server process terminated before the initialization completed."
Reinstalling didnt help. Clicking on "Install / update Python environment using the bundled installer" hangs at "Installing".

## Reproduce

1.  Click on 'New session.'
2.  See error ' Failed to create session! Jupyter Server process terminated before the initialization completed'

## Expected behavior

New session should start

## Context

- Operating System and version: Windows 10
- JupyterLab-Desktop version: 3.6.3-1
- Installer: .exe

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
[2023-05-04 14:44:54.534] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:282:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2023-05-04 14:44:58.883] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:282:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2023-05-04 14:44:58.915] [error] (node:6972) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'protocol')
    at new LabView (C:\JupyterLab\resources\app.asar\build\out\main\labview\labview.js:45:50)
    at SessionWindow._loadLabView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:274:25)
    at SessionWindow._updateContentView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:680:18)
    at IpcMainImpl.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:421:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2023-05-04 14:44:58.941] [error] (node:6972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
</pre>
</details>

**Comment by mbektas** [comment]
@samuelvw01 looks like your server launch is failing but logs are not showing enough details. can you try these:
1. Launch server manually using Windows Terminal and check terminal logs. [Instructions here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#launching-jupyterlab-server-manually).
2. When JupyterLab Desktop is closed, install the Python environment directly by using the installer in `C:\JupyterLab\resources\env_installer`
3. If there are still errors, set log level to `debug`, retry launch and check and share `main.log` file by following [these instructions](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#logs).

**Comment by samuelvw01** [comment]
Launching server manually works without any errors. Installed Python environment (it says I had to delete jlab_server folder), but I got same error as above. Set log level to debug, here is my main.log
[main.log](https://github.com/jupyterlab/jupyterlab-desktop/files/11400489/main.log)

**Comment by mbektas** [comment]
Interesting, it was expected to error out in the same way when you tried manually. Did you activate the environment before launching the server manually? you can do so using:
- `cd %APPDATA%\jupyterlab-desktop\jlab_server`
- `condabin\activate.bat`

**Comment by samuelvw01** [comment]
Thanks, that worked! (There were some conflicts during conda constructor phase, but I have resolved them). Now it runs as expected.
