### ISSUE TITLE
JupyterLab Desktop fails to launch on Windows with Python codec error

### ISSUE THREAD

**Issue by rfritz** [jupyterlab/jupyterlab-desktop#702]
## Description

When I try to launch from the command line, I get the following error:

```
C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs>jlab

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\Users\User\AppData\Roaming\jupyterlab-desktop\jlab_server\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\User\\AppData\\Roaming\\jupyterlab-desktop\\jlab_server\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\Users\\User\\AppData\\Roaming\\jupyterlab-desktop\\jlab_server\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\User\\AppData\\Roaming\\jupyterlab-desktop\\jlab_server\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Users\\User\\AppData\\Roaming\\jupyterlab-desktop\\jlab_server',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002e28 (most recent call first):
<no Python frame>

C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs>

```
## Reproduce

1. Install JupyterLab Desktop
2. Open "cmd"
3. Enter "jlab"
4. Observe error

## Expected behavior

JupyterLab Desktop starts

## Context

- Operating System and version:  Windows 10 Pro, 22H2, build 19045.3324
- JupyterLab-Desktop version: 4.0.5.0
- Installer: .exe
- 

<details><summary>Troubleshoot Output</summary>
<pre>
[main.log](https://github.com/jupyterlab/jupyterlab-desktop/files/12541351/main.log)

It never gets that far.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
[2023-01-12 19:50:17.982] [info]  In production mode

[2023-01-12 19:50:18.012] [info]  Logging to file (C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level

[2023-01-12 19:50:18.387] [error] (node:12888) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)

[2023-01-12 20:05:03.726] [info]  In production mode

[2023-01-12 20:05:03.749] [info]  Logging to file (C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level

[2023-01-12 20:05:04.121] [error] (node:19024) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)

[2023-01-12 20:05:58.253] [warn]  Error: Failed to launch Jupyter Server
    at C:\JupyterLab\resources\app.asar\build\out\main\server.js:260:28

[2023-01-12 20:06:21.863] [verbose] Starting application in workspace: "default"

[2023-01-12 20:11:59.400] [info]  In production mode

[2023-01-12 20:11:59.422] [info]  Logging to file (C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level

[2023-01-12 20:11:59.790] [error] (node:16336) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)

[2023-01-12 20:12:49.145] [warn]  Error: Failed to launch Jupyter Server
    at C:\JupyterLab\resources\app.asar\build\out\main\server.js:260:28

[2023-01-12 20:13:01.953] [verbose] Starting application in workspace: "default"

[2023-03-07 12:01:45.448] [info]  In production mode

[2023-03-07 12:01:45.490] [info]  Logging to file (C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level

[2023-03-07 12:01:45.585] [error] (node:18228) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)

[2023-03-07 12:02:03.436] [verbose] Starting application in workspace: "default"

[2023-03-09 15:11:09.585] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:285:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

[2023-03-09 15:19:33.566] [error] Failed to create free server Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

[2023-03-09 15:19:33.569] [error] (node:17488) UnhandledPromiseRejectionWarning: Error: No default environment found!
    at C:\JupyterLab\resources\app.asar\build\out\main\registry.js:191:32
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)

[2023-03-09 15:19:33.570] [error] (node:17488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

[2023-03-09 15:24:56.218] [error] undefined

[2023-03-09 15:24:56.251] [error] TypeError: Cannot read properties of undefined (reading 'openSession')
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:238:32)
    at App.emit (node:events:513:28)
    at new SessionWindow (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:101:22)
    at SessionWindowManager.createNew (C:\JupyterLab\resources\app.asar\build\out\main\app.js:115:24)
    at SessionWindowManager.createNewEmptyWindow (C:\JupyterLab\resources\app.asar\build\out\main\app.js:56:21)
    at JupyterApplication.startup (C:\JupyterLab\resources\app.asar\build\out\main\app.js:235:40)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:201:14)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-03-09 15:37:29.075] [warn]  Language pack 'English_United States' not valid!

[2023-03-09 15:37:51.533] [warn]  Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time

[2023-03-09 16:21:13.042] [warn]  Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time

[2023-03-09 16:57:21.706] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 16:57:21.948] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 16:57:21.950] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 17:05:46.820] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 17:05:52.117] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 17:06:03.214] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 20:17:54.844] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 20:17:54.872] [warn]  Connection lost, reconnecting in 0 seconds.

[2023-03-09 20:17:56.674] [error] (node:8088) UnhandledPromiseRejectionWarning: Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:285:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)

[2023-03-09 20:17:56.674] [error] (node:8088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

[2023-03-09 20:17:56.676] [error] (node:8088) UnhandledPromiseRejectionWarning: Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:285:28)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

[2023-03-09 20:17:56.676] [error] (node:8088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

[2023-05-28 12:55:43.118] [error] Failed to start server Error: Failed to launch Jupyter Server
    at C:\JupyterLab\resources\app.asar\build\out\main\server.js:263:28

[2023-05-28 12:56:33.155] [error] Failed to start server Error: Failed to launch Jupyter Server
    at C:\JupyterLab\resources\app.asar\build\out\main\server.js:263:28

[2023-05-28 12:56:33.186] [error] (node:20336) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'protocol')
    at new LabView (C:\JupyterLab\resources\app.asar\build\out\main\labview\labview.js:60:50)
    at SessionWindow._loadLabView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:282:25)
    at SessionWindow._updateContentView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:697:18)
    at IpcMainImpl.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:429:18)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)

[2023-05-28 12:56:33.190] [error] (node:20336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

[2023-05-28 13:56:49.536] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 13:57:13.271] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 13:57:59.850] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 13:58:47.658] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:01:58.386] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:11:18.734] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:11:56.162] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:29:43.980] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:30:11.875] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-05-28 14:30:57.426] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-06-07 20:41:31.889] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-06-07 20:42:05.126] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-06-07 20:42:20.008] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-06-07 20:55:10.455] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-07-05 17:45:27.285] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-07-05 17:45:49.627] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-07-05 17:46:10.560] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-08-03 20:40:55.695] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-08-03 20:41:17.754] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:303:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:166:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:176:26)
    at C:\JupyterLab\resources\app.asar\build\out\main\main.js:202:22

[2023-08-03 20:45:37.182] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-08-03 20:45:52.214] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-08-03 20:51:53.412] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-08-03 20:52:11.068] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-09-06 11:29:37.593] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-09-06 11:30:26.228] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-09-06 11:33:02.994] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-09-06 11:33:50.179] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

[2023-09-06 11:43:21.259] [info]  In production mode

[2023-09-06 11:43:21.261] [info]  Logging to file (C:\Users\User\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'debug' level

[2023-09-06 11:43:21.323] [error] SyntaxError: Unexpected token 'E', "EXEC:ERROR" is not valid JSON
    at JSON.parse (<anonymous>)
    at Registry.getEnvironmentInfoSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:311:30)
    at Registry._resolveEnvironmentSync (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:169:26)
    at new Registry (C:\JupyterLab\resources\app.asar\build\out\main\registry.js:68:33)
    at new JupyterApplication (C:\JupyterLab\resources\app.asar\build\out\main\app.js:175:26)
    at App.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\main.js:180:22)

</pre>
</details>

**Comment by mbektas** [comment]
@rfritz does it work when you launch from GUI? can you also try launching `jlab --log-level debug` to get more detailed logs.

by the way, you can try [this new version ](https://github.com/jupyterlab/jupyterlab-desktop/actions/runs/6401865223)(work in progress) which should show more details on the execution error (`EXEC:ERROR` above).

**Comment by rfritz** [comment]
Thanks for the reply.

On Wed, Oct 4, 2023, 11:49 AM Mehmet Bektas ***@***.***>
wrote:

> @rfritz <https://github.com/rfritz> does it work when you launch from
> GUI?
>
No. I think I tried all the obvious things.

I'm away from my office right now; I'll do more testing when I get back.

**Comment by rfritz** [comment]
The new version you linked, version 4.0.6.0, seems to fix the problem, as
does version 4.0.7-1. Hopefully, when it is formally released, the problem
will stay fixed.
-- 
Randolph M. Fritz || ***@***.***

**Comment by mbektas** [comment]
closing since 4.0.7-1 is available now. please create a new issue if problem persists.

**Comment by rfritz** [comment]
And, indeed, the formally released version continues to work.

Thank you!
-- 
Randolph M. Fritz || ***@***.***
