### ISSUE TITLE
electron-28 fails to start jupyterlab-desktop

### ISSUE THREAD

**Issue by PF4Public** [jupyterlab/jupyterlab-desktop#786]
Starting `jupyterlab-desktop` with electron-28 fails with the following error:
```sh
16:37:22.419 › TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.isDevMode (***/jupyterlab-desktop/build/out/main/utils.js:43:25)
    at ***/jupyterlab-desktop/build/out/main/main.js:192:55
    at new Promise (<anonymous>)
    at processArgs (***/jupyterlab-desktop/build/out/main/main.js:191:12)
    at App.<anonymous> (***/jupyterlab-desktop/build/out/main/main.js:169:15)
    at App.emit (node:events:517:28)
16:37:22.423 › null
16:37:22.424 › TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.isDevMode (***/jupyterlab-desktop/build/out/main/utils.js:43:25)
    at getLogLevel (***/jupyterlab-desktop/build/out/main/main.js:55:17)
    at redirectConsoleToLog (***/jupyterlab-desktop/build/out/main/main.js:71:22)
    at App.<anonymous> (***/jupyterlab-desktop/build/out/main/main.js:178:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This does not happen if starting with electron-27. I've hardcoded `isDevMode()` to always return `false`, which solved this issue for me.

I could not find the exact braking change which might've occured between those electron/node versions, it could very well be something on my system. Would you be able to verify whether you can also reproduce this issue?

**Comment by JasonWeill** [comment]
@PF4Public Where are you seeing this issue? Are you trying to build JupyterLab Desktop locally or are you running a version that you downloaded and installed as a release? Thanks!

**Comment by PF4Public** [comment]
I'm building it locally. It builds, but does not start with electron-28.

**Comment by mbektas** [comment]
@PF4Public is there any particular reason you are trying to upgrade to electron 28? we are currently at electron 27.

**Comment by mbektas** [comment]
It is probably failing due to [ESM module support ](https://www.electronjs.org/blog/electron-28-0#highlights)added to electron 28.

**Comment by PF4Public** [comment]
> @PF4Public is there any particular reason you are trying to upgrade to electron 28? we are currently at electron 27.

I'm trying to keep a single electron binary in the system and build every application I use against that, not using the shipped electron binaries. I haven't yet tested electron-29 as I expect many breakages. But 28 looks solid amongst others.

> It is probably failing due to [ESM module support ](https://www.electronjs.org/blog/electron-28-0#highlights)added to electron 28.

Sounds plausible, could it be fixed? As far as I understand, `require.main` became no longer accesible for whatever reason.

**Comment by mbektas** [comment]
we will take a more detailed look at this, once we upgrade to a higher electron version.

**Comment by PF4Public** [comment]
Same with electron-29 (just a FYI)

**Comment by notluquis** [comment]
Correcting my earlier comment here: I wrote that this still reproduces on master, and I had not tested it. It does not reproduce through the path I checked.

Probe on the Electron this repo ships, 42.5.0, launching a directory app the way `yarn start` does, evaluating master's exact expression:

```
isDevMode(master) = true
require.main      = electron        <- defined, not undefined
defaultApp        = true
isPackaged        = false
```

No throw. The upstream cause, electron/electron#40501 (`require.main` undefined after the ESM work), was closed in December 2023, which fits: the reports here are against Electron 28, and 42 is well past it. What I verified is macOS, the bundled binary, and the default-app path. A system Electron on FreeBSD or Linux is not covered by that probe, so if anyone can still reproduce it there, that is worth posting.

What remains true regardless of whether it currently throws:

```ts
return require.main.filename.indexOf('app.asar') === -1;
```

`require.main.filename` being the string `electron` is an undocumented Electron internal that already broke once. `app.isPackaged` is the documented API for the same question. #1097 makes that change, and the case for it is the fragility rather than a live crash, which is how the PR should have been argued in the first place.

Worked through this with Claude Code; the probe above was run here, and the earlier claim was an inference from the line being unchanged rather than a reproduction.
