### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ' ', "          "... is not valid JSON

### ISSUE THREAD

**Issue by avivazran** [jupyterlab/jupyterlab-desktop#840]
[2024-06-17 13:14:41.490] [error] Failed to check for updates: FetchError: request to https://objects.githubusercontent.com/github-production-release-asset-2e65be/90307576/894aa178-65eb-4a1c-b18d-8d559cb96874?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240617%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240617T101441Z&X-Amz-Expires=300&X-Amz-Signature=b3c8d59651dd7a61749d9cb251e880d9871229ca2f319fe39b5c2e5bd48c579a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=90307576&response-content-disposition=attachment%3B%20filename%3Dlatest.yml&response-content-type=application%2Foctet-stream failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\JupyterLab\resources\app.asar\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-06-17 13:14:42.287] [error] (node:2660) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'workingDirectory')
    at C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:1031:55
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2024-06-17 13:14:42.288] [error] (node:2660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2024-06-17 13:14:42.292] [error] Handling request in the main instance.
[2024-06-17 13:15:04.892] [info]  In production mode
[2024-06-17 13:15:04.896] [info]  Logging to file (C:\Users\aazran\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'debug' level
[2024-06-17 13:15:08.336] [error] Failed to create free server SyntaxError: Unexpected token ' ', "          "... is not valid JSON
    at JSON.parse (<anonymous>)
    at WorkspaceSettings.read (C:\JupyterLab\resources\app.asar\build\out\main\config\settings.js:253:31)
    at new WorkspaceSettings (C:\JupyterLab\resources\app.asar\build\out\main\config\settings.js:221:14)
    at new JupyterServer (C:\JupyterLab\resources\app.asar\build\out\main\server.js:190:28)
    at JupyterServerFactory._createServer (C:\JupyterLab\resources\app.asar\build\out\main\server.js:567:21)
    at JupyterServerFactory.createFreeServer (C:\JupyterLab\resources\app.asar\build\out\main\server.js:469:21)
[2024-06-17 13:15:13.606] [error] Failed to check for updates: FetchError: request to https://objects.githubusercontent.com/github-production-release-asset-2e65be/90307576/894aa178-65eb-4a1c-b18d-8d559cb96874?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240617%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240617T101441Z&X-Amz-Expires=300&X-Amz-Signature=b3c8d59651dd7a61749d9cb251e880d9871229ca2f319fe39b5c2e5bd48c579a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=90307576&response-content-disposition=attachment%3B%20filename%3Dlatest.yml&response-content-type=application%2Foctet-stream failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\JupyterLab\resources\app.asar\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-06-17 13:16:14.667] [error] (node:20912) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ' ', "          "... is not valid JSON
    at JSON.parse (<anonymous>)
    at WorkspaceSettings.read (C:\JupyterLab\resources\app.asar\build\out\main\config\settings.js:253:31)
    at new WorkspaceSettings (C:\JupyterLab\resources\app.asar\build\out\main\config\settings.js:221:14)
    at IpcMainImpl.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:415:32)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88262)
    at WebContents.emit (node:events:514:28)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2024-06-17 13:16:14.669] [error] (node:20912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by JasonWeill** [comment]
Let's keep the conversation going in #824, which concerns the same issue, and where you've already commented.
