### ISSUE TITLE
Jupyter server process terminated before the initialization completed

### ISSUE THREAD

**Issue by Hedge90** [jupyterlab/jupyterlab-desktop#847]
## Description

When trying to create a new notebook, I get the error in the subject line. Clean installation on Windows 10, every path is set correctly.

## Context

- Operating System and version: Windows 10
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
[2024-07-18 11:30:04.227] [info]  In production mode
[2024-07-18 11:30:04.228] [info]  Logging to file (C:\Users\Kristóf\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'verbose' level
[2024-07-18 11:30:05.493] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:295:28)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
[2024-07-18 11:30:29.176] [info]  In production mode
[2024-07-18 11:30:29.177] [info]  Logging to file (C:\Users\Kristóf\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'debug' level
[2024-07-18 11:30:30.359] [debug] Server launch script:

        CALL cd /d "C:\Users\Kristóf\AppData\Roaming\jupyterlab-desktop\jlab_server\condabin"
        CALL activate.bat
        
        CALL cd /d "C:\Users\Kristóf"
        CALL python -m jupyterlab --no-browser --expose-app-in-browser --ServerApp.port=53875 --ServerApp.password="" --ServerApp.token="jlab:srvr:84cac6a9e8d9d627a249cc75b9adcb825d73de" --LabApp.quit_button=False --JupyterApp.config_file_name="" --ContentsManager.allow_hidden=True
[2024-07-18 11:30:30.359] [debug] Server launch parameters:
  [script]: C:\Users\KRISTF~1\AppData\Local\Temp\jlab_desktopHt6zbG\launch.bat
  [options]: {"cwd":"C:\\Users\\Kristóf","shell":"cmd.exe","env":{"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\Kristóf\\AppData\\Roaming","ChocolateyInstall":"C:\\ProgramData\\chocolatey","ChocolateyLastPathUpdate":"133607563385275124","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"DESKTOP-DQQ6PLQ","ComSpec":"C:\\Windows\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\Kristóf","IntelliJ IDEA":"C:\\Program Files\\JetBrains\\IntelliJ IDEA 2024.1.1\\bin;","IntelliJ IDEA Community Edition":"C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2024.1.1\\bin;","JAVA_HOME":"C:\\Program Files (x86)\\Java\\jre-1.8","LOCALAPPDATA":"C:\\Users\\Kristóf\\AppData\\Local","LOGONSERVER":"\\\\DESKTOP-DQQ6PLQ","NUMBER_OF_PROCESSORS":"16","OneDrive":"C:\\Users\\Kristóf\\OneDrive","OneDriveConsumer":"C:\\Users\\Kristóf\\OneDrive","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","Path":"C:\\Users\\Kristóf\\AppData\\Local\\Programs\\mongosh;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\MinGW\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\JupyterLab;C:\\Program Files\\MongoDB\\Server\\7.0\\bin;C:\\Program Files\\Erlang OTP\\bin;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Python\\Python312\\;C:\\Users\\Kristóf\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\IntelliJ IDEA 2024.1.1\\bin;;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2024.1.1\\bin;;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Kristóf\\AppData\\Roaming\\npm;C:\\MinGW\\bin;C:\\Flutter\\flutter\\bin;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\mongosh\\;","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD","PROCESSOR_LEVEL":"25","PROCESSOR_REVISION":"4401","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\Windows","TEMP":"C:\\Users\\KRISTF~1\\AppData\\Local\\Temp","TMP":"C:\\Users\\KRISTF~1\\AppData\\Local\\Temp","TWITTER_ACCESS_TOKEN":"-","TWITTER_ACCESS_TOKEN_SECRET":"-","TWITTER_API_KEY":"-","TWITTER_API_SECRET_KEY":"-","USERDOMAIN":"DESKTOP-DQQ6PLQ","USERDOMAIN_ROAMINGPROFILE":"DESKTOP-DQQ6PLQ","USERNAME":"Kristóf","USERPROFILE":"C:\\Users\\Kristóf","windir":"C:\\Windows","JUPYTER_CONFIG_DIR":"C:\\Users\\Kristóf\\AppData\\Roaming\\jupyterlab-desktop","JUPYTERLAB_WORKSPACES_DIR":"C:\\Users\\Kristóf\\.jupyter\\desktop-workspaces"}}
[2024-07-18 11:30:30.465] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:295:28)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
[2024-07-18 11:30:31.908] [debug] Server launch script:

        CALL cd /d "C:\Users\Kristóf\AppData\Roaming\jupyterlab-desktop\jlab_server\condabin"
        CALL activate.bat
        
        CALL cd /d "C:\Users\Kristóf"
        CALL python -m jupyterlab --no-browser --expose-app-in-browser --ServerApp.port=53882 --ServerApp.password="" --ServerApp.token="jlab:srvr:a1da528c01aeedb1873c0e31e4f6e07bc12efd" --LabApp.quit_button=False --JupyterApp.config_file_name="" --ContentsManager.allow_hidden=True
[2024-07-18 11:30:31.908] [debug] Server launch parameters:
  [script]: C:\Users\KRISTF~1\AppData\Local\Temp\jlab_desktop7BTQWc\launch.bat
  [options]: {"cwd":"C:\\Users\\Kristóf","shell":"cmd.exe","env":{"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\Kristóf\\AppData\\Roaming","ChocolateyInstall":"C:\\ProgramData\\chocolatey","ChocolateyLastPathUpdate":"133607563385275124","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"DESKTOP-DQQ6PLQ","ComSpec":"C:\\Windows\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\Kristóf","IntelliJ IDEA":"C:\\Program Files\\JetBrains\\IntelliJ IDEA 2024.1.1\\bin;","IntelliJ IDEA Community Edition":"C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2024.1.1\\bin;","JAVA_HOME":"C:\\Program Files (x86)\\Java\\jre-1.8","LOCALAPPDATA":"C:\\Users\\Kristóf\\AppData\\Local","LOGONSERVER":"\\\\DESKTOP-DQQ6PLQ","NUMBER_OF_PROCESSORS":"16","OneDrive":"C:\\Users\\Kristóf\\OneDrive","OneDriveConsumer":"C:\\Users\\Kristóf\\OneDrive","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","Path":"C:\\Users\\Kristóf\\AppData\\Local\\Programs\\mongosh;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\MinGW\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\JupyterLab;C:\\Program Files\\MongoDB\\Server\\7.0\\bin;C:\\Program Files\\Erlang OTP\\bin;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Python\\Python312\\;C:\\Users\\Kristóf\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\IntelliJ IDEA 2024.1.1\\bin;;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2024.1.1\\bin;;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Kristóf\\AppData\\Roaming\\npm;C:\\MinGW\\bin;C:\\Flutter\\flutter\\bin;C:\\Users\\Kristóf\\AppData\\Local\\Programs\\mongosh\\;","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD","PROCESSOR_LEVEL":"25","PROCESSOR_REVISION":"4401","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\Windows","TEMP":"C:\\Users\\KRISTF~1\\AppData\\Local\\Temp","TMP":"C:\\Users\\KRISTF~1\\AppData\\Local\\Temp","TWITTER_ACCESS_TOKEN":"-","TWITTER_ACCESS_TOKEN_SECRET":"-","TWITTER_API_KEY":"-","TWITTER_API_SECRET_KEY":"-","USERDOMAIN":"DESKTOP-DQQ6PLQ","USERDOMAIN_ROAMINGPROFILE":"DESKTOP-DQQ6PLQ","USERNAME":"Kristóf","USERPROFILE":"C:\\Users\\Kristóf","windir":"C:\\Windows","JUPYTER_CONFIG_DIR":"C:\\Users\\Kristóf\\AppData\\Roaming\\jupyterlab-desktop","JUPYTERLAB_WORKSPACES_DIR":"C:\\Users\\Kristóf\\.jupyter\\desktop-workspaces"}}
[2024-07-18 11:30:31.982] [error] Failed to start server Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:295:28)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
[2024-07-18 11:30:31.984] [error] (node:18020) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'protocol')
    at new LabView (C:\JupyterLab\resources\app.asar\build\out\main\labview\labview.js:46:50)
    at SessionWindow._loadLabView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:275:25)
    at SessionWindow._updateContentView (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:873:18)
    at IpcMainImpl.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\sessionwindow\sessionwindow.js:438:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `JupyterLab --trace-warnings ...` to show where the warning was created)
[2024-07-18 11:30:31.985] [error] (node:18020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

</pre>
</details>

**Comment by JasonWeill** [comment]
@mbektas It looks like this is an error specific to JupyterLab Desktop, not JupyterLab. Anything that @Hedge90 should check?

**Comment by JasonWeill** [comment]
@Hedge90 Which version(s) of JupyterLab Desktop do you see this error on? Thanks!

**Comment by notluquis** [comment]
Traced against master. The cause is not settled without a Windows machine, but the reason it is not settled is itself a finding.

**The failure surface throws away everything that would identify it.** `server.ts:311` is `execFile(launchScriptPath, execOptions)` with no callback, nothing ever subscribes to the child's `stdout` or `stderr`, and the exit handler at `:327` is `() => {}`, so `code` and `signal` are discarded too. The dialog is `String(error)`. `ModuleNotFoundError: No module named jupyterlab`, `The system cannot find the path specified` and a conda traceback all render as the same sentence, and the log cannot even state the exit code.

**Two different strings, two different paths**, which is worth separating because they get used interchangeably:

| String | Path | Meaning |
| --- | --- | --- |
| `Failed to launch Jupyter Server` | `server.ts:313-325`, the timeout won the race | child alive at 30s, never answered on the port |
| `terminated before the initialization completed` | `server.ts:327-352`, `exit` fired with `started === false` | child exited fast |

This report is the second, dead in 74 to 106 ms, on the bundled conda env with a fully quoted script.

**Ranked candidates**, both keyed on the non-ASCII username in the log:

1. Batch encoding. `createTempFile` writes UTF-8 with no BOM and nothing sets `chcp`, so `cmd.exe` reads the script in the OEM codepage and `ó` mangles, the `cd` into `condabin` fails, and activation never happens. Corroborating detail from the log itself: Windows handed the app `TEMP=C:\Users\KRISTF~1\...`, the 8.3 short name, while the app writes the long non-ASCII name into the script body. Same mechanism as #808.
2. The bundled env broken at install time by the non-ASCII prefix. There is already a comment at `utils.ts:80` that the install directory cannot contain spaces for conda.

**What turns any of these into a silent wrong-interpreter launch** is `server.ts:47`:

```ts
const launchArgs = ['python', '-m', 'jupyterlab'];
```

Bare `python`, not the resolved interpreter, and `CALL` does not abort a batch when it fails. So a failed activation does not error, it launches whatever `python` is on `PATH`.

**The third error in that log is a cascade, not a cause.** `Cannot read properties of undefined (reading 'protocol')` fires after the user already saw the dialog: the catch at `sessionwindow.ts:585` shows the progress view and then falls through with no `return` to `:605-606`, which set `ContentViewType.Lab` and load the lab view, where `sessionConfig.url` is still undefined because it is only assigned after the server starts. Same missing `return` leaves the window at `Lab` with no lab view, which is the precondition for the `uiMode` crash in #857.

**One artifact settles it.** `server.ts:319` unlinks the script only on success, so after a failure `launch.bat` survives in `%TEMP%\jlab_desktop*\`. From a fresh `cmd`: run `chcp`, hex-dump that file, then run it and paste all output plus `echo %ERRORLEVEL%`. That output is exactly what `execFile` discards today.

Traced with Claude Code. The code paths are read from master and the two error strings mapped to their branches; nothing Windows-specific was executed, since this was done on macOS.
